include $(MY_LIBTT)/default.mk

all: cmake build

run:
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_cereal.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_cmdline.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_eigen.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_glm.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_json11.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_opencv.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_stb.exe

