all:

run:
	print_versions.py
	sample_argparse.py
	sample_json.py
	sample_matplotlib.py
	sample_numpy.py
	sample_os.py
	sample_string.py
	sample_syntax.py
	sample_text.py
	test_common.py

run-n:
	sample_kivy.py
	sample_skimage.py

clean:
	myclean.sh -rm -py

