include $(MY_LIBTT_WIN)/makefile.mk

run:
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_c++11.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_c++14.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_c++17.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_class.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_cstdio.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_fstream.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_syntax.exe
	cd $(BUILD_DIR) && $(BUILD_CONFIG)/sample_thread.exe

